import type { Product } from "@/types/product"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Wireless Headphones",
    description: "Premium noise-cancelling wireless headphones with 30-hour battery life",
    price: 199.99,
    category: "Electronics",
    stock: 45,
  },
  {
    id: "2",
    name: "Smart Watch",
    description: "Fitness tracker with heart rate monitor and sleep tracking",
    price: 149.99,
    category: "Electronics",
    stock: 32,
  },
  {
    id: "3",
    name: "Cotton T-Shirt",
    description: "Soft, breathable cotton t-shirt available in multiple colors",
    price: 24.99,
    category: "Clothing",
    stock: 120,
  },
  {
    id: "4",
    name: "Ergonomic Office Chair",
    description: "Adjustable office chair with lumbar support and breathable mesh back",
    price: 249.99,
    category: "Home",
    stock: 18,
  },
  {
    id: "5",
    name: "Stainless Steel Water Bottle",
    description: "Vacuum insulated water bottle that keeps drinks cold for 24 hours",
    price: 34.99,
    category: "Home",
    stock: 65,
  },
  {
    id: "6",
    name: "Wireless Charging Pad",
    description: "Fast wireless charger compatible with all Qi-enabled devices",
    price: 29.99,
    category: "Electronics",
    stock: 53,
  },
  {
    id: "7",
    name: "Denim Jeans",
    description: "Classic straight-fit jeans with stretch comfort technology",
    price: 59.99,
    category: "Clothing",
    stock: 85,
  },
  {
    id: "8",
    name: "Bestselling Novel",
    description: "Award-winning fiction novel by a renowned author",
    price: 19.99,
    category: "Books",
    stock: 110,
  },
  {
    id: "9",
    name: "Bluetooth Speaker",
    description: "Portable waterproof speaker with 360° sound and 12-hour battery life",
    price: 79.99,
    category: "Electronics",
    stock: 28,
  },
  {
    id: "10",
    name: "Ceramic Coffee Mug Set",
    description: "Set of 4 handcrafted ceramic coffee mugs in assorted colors",
    price: 39.99,
    category: "Home",
    stock: 42,
  },
  {
    id: "11",
    name: "Yoga Mat",
    description: "Non-slip exercise mat with carrying strap",
    price: 29.99,
    category: "Home",
    stock: 37,
  },
  {
    id: "12",
    name: "Cookbook",
    description: "Collection of 100 easy and healthy recipes",
    price: 24.99,
    category: "Books",
    stock: 55,
  },
  {
    id: "13",
    name: "Winter Jacket",
    description: "Waterproof and windproof jacket with thermal lining",
    price: 129.99,
    category: "Clothing",
    stock: 23,
  },
  {
    id: "14",
    name: "Tablet",
    description: "10-inch HD display tablet with 64GB storage",
    price: 299.99,
    category: "Electronics",
    stock: 19,
  },
  {
    id: "15",
    name: "LED Desk Lamp",
    description: "Adjustable desk lamp with multiple brightness levels",
    price: 49.99,
    category: "Home",
    stock: 31,
  },
]
